# answers = {
#     1: ["richtig", "falsch1", "flasch2", "falsch3"],
#     2: ["richtig", "falsch1", "flasch2", "falsch3"],
#     3: ["richtig", "falsch1", "flasch2", "falsch3"],
#     4: ["richtig", "falsch1", "flasch2", "falsch3"],
#     5: ["richtig", "falsch1", "flasch2", "falsch3"],
#     6: ["richtig", "falsch1", "flasch2", "falsch3"],
#     7: ["richtig", "falsch1", "flasch2", "falsch3"],
#     8: ["richtig", "falsch1", "flasch2", "falsch3"],
#     9: ["richtig", "falsch1", "flasch2", "falsch3"],
#     10: ["richtig", "falsch1", "flasch2", "falsch3"],
#     11: ["richtig", "falsch1", "flasch2", "falsch3"],
#     12: ["richtig", "falsch1", "flasch2", "falsch3"],
#     13: ["richtig", "falsch1", "flasch2", "falsch3"],
#     14: ["richtig", "falsch1", "flasch2", "falsch3"],
#     15: ["richtig", "falsch1", "flasch2", "falsch3"],
#     16: ["richtig", "falsch1", "flasch2", "falsch3"],
#     17: ["richtig", "falsch1", "flasch2", "falsch3"],
#     18: ["richtig", "falsch1", "flasch2", "falsch3"],
#     19: ["richtig", "falsch1", "flasch2", "falsch3"],
#     20: ["richtig", "falsch1", "flasch2", "falsch3"],
# }

# answers = {
#     1: ["Feuerlöschgerät", "Notausgang", "Sammelstelle", "Warnung vor radioaktiven Stoffen"],
#     2: ["Anleitermöglichkeit", "Giftig", "Atemschutz benötigt", "Selbstentzündlich"],
#     3: ["Notausgang", "Feuerlöschgerät", "Ansteckungsgefährlich", "Nicht brennbares und nicht giftiges Gas"],
#     4: ["Sammelstelle", "Explosionsgefährlich", "Entzündbarer flüssiger Stoff", "Ätzend"],
#     5: ["Warnung vor explosionsfähiger Atmosphäre", "Mobilfunk verboten", "Giftig", "Warntafel für tiefgekühlt verflüssigtes Gas"],
#     6: ["Warnung vor radioaktiven Stoffen oder ionisierenden Strahlen", "Sammelstelle", "Feuerlöschgerät", "Anleitermöglichkeit"],
#     7: ["Warnung vor gesundheitsschädlichen oder reizenden Stoffen", "Atemschutz benötigt", "Warntafel für leicht entzündbaren flüssigen Stoff", "Selbstentzündlich"],
#     8: ["Ätzend", "Nicht brennbares und nicht giftiges Gas", "Warnung vor radioaktiven Stoffen", "Sammelstelle"],
#     9: ["Giftig", "Feuerlöschgerät", "Anleitermöglichkeit", "Mobilfunk verboten"],
#     10: ["Atemschutz benötigt", "Ansteckungsgefährlich", "Warntafel für tiefgekühlt verflüssigtes Gas", "Sammelstelle"],
#     11: ["Mobilfunk verboten", "Notausgang", "Feuerlöschgerät", "Sammelstelle"],
#     12: ["Explosionsgefährlich", "Warnung vor gesundheitsschädlichen Stoffen", "Warntafel für entzündbaren flüssigen Stoff", "Giftig"],
#     13: ["Entzündbarer flüssiger Stoff", "Mobilfunk verboten", "Atemschutz benötigt", "Anleitermöglichkeit"],
#     14: ["Nicht brennbares und nicht giftiges Gas", "Ätzend", "Giftig", "Feuerlöschgerät"],
#     15: ["Selbstentzündlich", "Anleitermöglichkeit", "Notausgang", "Warnung vor radioaktiven Stoffen"],
#     16: ["Ansteckungsgefährlich", "Warntafel für leicht entzündbaren flüssigen Stoff", "Mobilfunk verboten", "Sammelstelle"],
#     17: ["Verschiedene gefährliche Stoffe", "Entzündbarer flüssiger Stoff", "Atemschutz benötigt", "Explosionsgefährlich"],
#     18: ["Warntafel für tiefgekühlt verflüssigtes Gas", "Ätzend", "Anleitermöglichkeit", "Giftig"],
#     19: ["Warntafel für entzündbaren flüssigen Stoff", "Sammelstelle", "Nicht brennbares und nicht giftiges Gas", "Explosionsgefährlich"],
#     20: ["Warntagel für leicht entzündbaren flüssigen Stoff", "Giftig", "Warnung vor radioaktiven Stoffen", "Anleitermöglichkeit"],
# }

answers = {
    1: ["Feuerlöschgerät", "Feuermelder", "Feuerlöscher", "Brandmelder"],
    2: ["Anleitermöglichkeit", "Leiteraufstieg", "Steighilfe", "Trittplattform"],
    3: ["Notausgang", "Fluchtweg", "Notfalltür", "Rettungsweg"],
    4: ["Sammelstelle", "Treffpunkt", "Rettungszone", "Sammelplatz"],
    5: ["Warnung vor explosionsfähiger Atmosphäre", "Warnung vor giftigen Gasen", "Warnung vor explosiven Stoffen", "Gefahr explosiver Dämpfe"],
    6: ["Warnung vor radioaktiven Stoffen oder ionisierenden Strahlen", "Warnung vor chemischen Substanzen", "Gefahr durch ionisierende Strahlen", "Warnung vor elektromagnetischen Strahlen"],
    7: ["Warnung vor gesundheitsschädlichen oder reizenden Stoffen", "Warnung vor ätzenden Stoffen", "Warnung vor giftigen Gasen", "Gefahr durch reizende Substanzen"],
    8: ["Ätzend", "Reizend", "Giftig", "Schädlich"],
    9: ["Giftig", "Ätzend", "Reizend", "Gefahrstoff"],
    10: ["Atemschutz benötigt", "Schutzmaske erforderlich", "Gasmaske nötig", "Schutz vor giftigen Dämpfen"],
    11: ["Mobilfunk verboten", "Handynutzung untersagt", "Funkgeräte verboten", "Nutzung elektronischer Geräte verboten"],
    12: ["Explosionsgefährlich", "Entzündlich", "Gefahr der Explosion", "Gefahr durch Druckbehälter"],
    13: ["Entzündbarer flüssiger Stoff", "Brennbarer flüssiger Stoff", "Gefahr durch entzündliche Flüssigkeiten", "Flüssigkeiten leicht entflammbar"],
    14: ["Nicht brennbares und nicht giftiges Gas", "Ungiftiges Gas", "Inertes Gas", "Nicht entzündliches Gas"],
    15: ["Selbstentzündlich", "Leicht entflammbar", "Schnell entzündlich", "Gefahr der Selbstentzündung"],
    16: ["Ansteckungsgefährlich", "Biogefährdung", "Infektionsrisiko", "Gefahr durch Krankheitserreger"],
    17: ["Verschiedene gefährliche Stoffe", "Mischung gefährlicher Stoffe", "Mehrere Gefahrstoffe", "Gefahrgut-Mix"],
    18: ["Warntafel für tiefgekühlt verflüssigtes Gas", "Warntafel für unter Druck stehendes Gas", "Gefahr durch verflüssigte Gase", "Warnschild für tiefgekühlte Stoffe"],
    19: ["Warntafel für entzündbaren flüssigen Stoff", "Warntafel für leicht brennbare Flüssigkeiten", "Warnschild für flüssige Brennstoffe", "Gefahr durch entflammbare Flüssigkeiten"],
    20: ["Warntafel für leicht entzündbaren flüssigen Stoff", "Warntafel für hochentzündliche Flüssigkeiten", "Gefahr durch extrem entflammbare Flüssigkeiten", "Warnschild für schnell entzündbare Flüssigkeiten"],
}
