fragen = {
    1 : "Feuerlöschgerät",
    2 : "Anleitermöglichkeit",
    3 : "Notausgang",
    4 : "Sammelstelle",
    5 : "Warnung vor explosionsfähiger Atmosphäre",
    6 : "Warnung vor radioaktiven Stoffen oder ionisierenden Strahlen",
    7 : "Warnung vor gesundheitsschädlichen oder reizenden Stoffen",
    8 : "Ätzend",
    9 : "Giftig",
    10 : "Atemschutz benötigt",
    11 : "Mobilfunk verboten",
    12 : "Explosionsgefährlich",
    13 : "Entzündbarer flüssiger Stoff",
    14 : "Nicht brennbares und nicht giftiges Gas",
    15 : "Selbstentzündlich",
    16 : "Ansteckungsgefährlich",
    17 : "Verschiedene gefährliche Stoffe",
    18 : "Warntafel für tiefgekühlt verflüssigtes Gas",
    19 : "Warntafel für entzündbaren flüssigen Stoff",
    20 : "Warntagel für leicht entzündbaren flüssigen Stoff"
}